services:
  - type: web
    name: career-predictor
    env: python
    plan: free

    buildImage: python:3.11

    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
